#!/usr/bin/env python3
"""Export the storefront catalogue (styles, variants, stores, floor stock) as one JSON file.

The demo online store on ravichanduedru.me/yuktikara is built from this file, so what the shop shows
is exactly what the dataset holds. Standard library only.

Usage: python scripts/export_storefront.py --out <path>/catalog.json
"""

from __future__ import annotations

import argparse
import csv
import json
import re
from collections import Counter, defaultdict
from pathlib import Path

SALES_STATUSES = {"Completed", "Shipped"}
# A style earns a fit note when most of its accepted returns say "Too small", as a real shop would learn
# from its returns desk. Only styles with enough returns to mean something qualify.
FIT_NOTE_SHARE = 0.5
FIT_NOTE_MIN_RETURNS = 30


def read(path: Path) -> list[dict]:
    with path.open(newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def main() -> int:
    parser = argparse.ArgumentParser(description="Export the Yuktikara storefront catalogue.")
    parser.add_argument("--data", default=str(Path(__file__).resolve().parent.parent / "data"))
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    data = Path(args.data)

    products = read(data / "Product.csv")
    variants = read(data / "ProductVariant.csv")
    stores = read(data / "Store.csv")
    orders = {o["OrderID"]: o for o in read(data / "SalesOrder.csv")}
    lines = read(data / "SalesOrderLine.csv")
    returns = read(data / "SalesReturn.csv")
    inventory = read(data / "StoreInventory.csv")
    manifest = json.loads((data / "manifest.json").read_text(encoding="utf-8"))
    totals = json.loads((data / "expected_answers.json").read_text(encoding="utf-8"))["totals"]

    units_sold: Counter[str] = Counter()
    for line in lines:
        if orders[line["OrderID"]]["OrderStatus"] in SALES_STATUSES:
            units_sold[line["ProductID"]] += int(line["Quantity"])

    reasons: dict[str, Counter[str]] = defaultdict(Counter)
    for r in returns:
        if r["ReturnStatus"] == "Accepted":
            reasons[r["ProductID"]][r["ReturnReasonID"]] += 1

    by_style: dict[str, list[dict]] = defaultdict(list)
    for v in variants:
        by_style[v["ProductID"]].append(v)

    rank = {pid: i + 1 for i, (pid, _) in enumerate(units_sold.most_common())}

    styles = []
    for p in products:
        vs = sorted(by_style[p["ProductID"]], key=lambda v: (v["ColorName"], int(v["SizeOrder"])))
        colors = list(dict.fromkeys(v["ColorName"] for v in by_style[p["ProductID"]]))
        sizes = [s for s, _ in sorted({(v["SizeCode"], int(v["SizeOrder"])) for v in vs}, key=lambda t: t[1])]
        counts = reasons[p["ProductID"]]
        total = sum(counts.values())
        fit_note = None
        if total >= FIT_NOTE_MIN_RETURNS and counts["RR1"] / total >= FIT_NOTE_SHARE:
            fit_note = "runs-small"
        styles.append({
            "id": p["ProductID"],
            "slug": slugify(p["ProductName"]),
            "name": p["ProductName"],
            "styleCode": p["StyleCode"],
            "department": p["DepartmentName"],
            "category": p["CategoryName"],
            "season": p["SeasonCode"],
            "price": float(p["ListPrice"]),
            "rfid": p["IsRfidTagged"] == "true",
            "colors": colors,
            "sizes": sizes,
            "variants": [{"id": v["VariantID"], "sku": v["SKU"], "color": v["ColorName"], "size": v["SizeCode"]}
                         for v in vs],
            "bestsellerRank": rank.get(p["ProductID"]),
            "fitNote": fit_note,
        })

    store_rows = [{
        "id": s["StoreID"],
        "name": s["StoreName"],
        "region": s["RegionName"],
        "city": s["City"],
        "state": s["StateCode"],
        "lat": float(s["Latitude"]),
        "lon": float(s["Longitude"]),
        "format": s["StoreFormat"],
        "squareFeet": int(s["SquareFeet"]),
        "opened": s["OpenedDate"],
    } for s in stores]

    # [variantId, storeId, floorQty, backroomQty, floorMinQty]: flat rows keep the JSON cheap to type.
    stock = sorted(
        [r["VariantID"], r["StoreID"], int(r["FloorQty"]), int(r["BackroomQty"]), int(r["FloorMinQty"])]
        for r in inventory
    )

    catalog = {
        "source": {
            "dataset": "Yuktikara Store",
            "period": manifest["period"],
            "stockSnapshot": inventory[0]["SnapshotDate"] if inventory else None,
            "note": "Generated by scripts/export_storefront.py from the Yuktikara Store dataset. All data is synthetic.",
        },
        # Headline figures from the oracle, for the architecture page's "one question, four answers".
        "figures": {
            "grossAllStatuses": float(totals["gross_all_statuses"]),
            "orderTotalSalesStatuses": float(totals["ordertotal_sales_statuses_includes_tax"]),
            "subtotalSalesStatuses": float(totals["subtotal_sales_statuses"]),
            "netSales": float(totals["net_sales"]),
            "orders": totals["order_count"],
            "lines": totals["line_count"],
            "returns": totals["return_count"],
        },
        "styles": styles,
        "stores": store_rows,
        "stock": stock,
    }

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(catalog, separators=(",", ":"), ensure_ascii=False) + "\n",
                   encoding="utf-8", newline="\n")
    flagged = [s["name"] for s in styles if s["fitNote"]]
    print(f"wrote {out}: {len(styles)} styles, {len(variants)} variants, {len(store_rows)} stores, "
          f"{len(inventory)} stock positions, {out.stat().st_size / 1024:.0f} KB")
    print(f"fit notes: {flagged or 'none'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
